### ISSUE TITLE
generate nix expression which can be built without running yarn outside nix beforehand

### ISSUE THREAD

**Issue by adrian-gierakowski** [stephank/yarn-plugin-nixify#6]
Hi, great work! I've been thinking about doing something like this since I first learned about yarn 2.

If I understand things correctly, in order to run `nix-build` in ci, I'd have to run `yarn` first in order to populate local `.yarn/cache`, since the generated `yarn-project.nix` reference files from that local directory. Would it be possible instead for the `cacheDrvs` to point at the remote sources from which `yarn` has downloaded the packages, so that nix could download them directly, eliminating the need to run `yarn` in ci? Thanks!

**Comment by stephank** [comment]
That's already the case. The nix build doesn't reference files in `.yarn/cache`, it provides those files. (In fact, this project doesn't work with the Yarn 'zero install' setup, where you commit `.yarn/cache`.)

Individual downloads in a Nix build are a bit slow, though. We currently invoke Yarn for each one, because it fetches a tarball, then converts it to a zip. So we invoke Yarn to ensure we get consistent output.
